// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace SimpleApp.DataLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Something : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Something));
        
        string IMigrationMetadata.Id
        {
            get { return "201602182134422_Something"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
